# Site settings
title: Rajahoster Cloud Hosting.
email: wooless.digital@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Cloud Hosting Indonesia. Pilihan terbaik untuk Anda 
  yang membutuhkan layanan hosting yang selalu online.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "rajahoster.com" # the base hostname & protocol for your site

# User setting
owner: Rajahoster.
email: wooless.digital@gmail.com
facebook_username: rajahoster
twitter_username: 
github_username: 
address:
  - line: Jln Pluit Dalam No 11, Penjaringan - Jakarta Utara. 14440
  # Feel free to add more lines here 
telephone: +62822-1111-9236
copyright: rajahoster.com | wooless digital 

# API settings
google_api_key:

# Build settings
markdown: kramdown